FrontEnd/FrontEnd/Models/ErrorViewModel.cs
using System;

namespace FrontEnd.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FrontEnd/FrontEnd/Models/SearchDTO.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace FrontEnd.Models
{
    public class SearchDTO
    {
        
        
            [Key]
            public long SearchID { get; set; }

            public string PostCode { get; set; }

            public double Longitude { get; set; }
            public double Latitude { get; set; }

            public string Region { get; set; }

            public string City { get; set; }

            public double DistanceToLondon { get; set; }

    }
    }

FrontEnd/FrontEnd/Controllers/HomeController.cs
using FrontEnd.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace FrontEnd.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FrontEnd/FrontEnd/Controllers/SearchDTOController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FrontEnd.Data;
using FrontEnd.Models;
using System.Net.Http;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using System.Net.Http.Formatting;

namespace FrontEnd.Controllers
{
    public class SearchDTOController : Controller
    {
        private readonly FrontEndContext _context;

        public SearchDTOController(FrontEndContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index(string searchString, bool? checkResp)
        {
            //  guarda o valor de KM / MILES
            // ViewBag.dist = false;

            // erro de ligacao / postalcode nao encontrado
            ViewBag.codebool = true;

            ViewData["CurrentFilter"] = searchString;

            var d = searchString;
            if (d == null)
            {
                return View();
            }
            try
            {

                using (var client = new HttpClient())


                {
                    // Request para pesquisar postal code (grava pesquisa na base de dados) 
                    var response = await client.GetAsync("https://localhost:44343/api/Searches/get/" + searchString);
                    response.EnsureSuccessStatusCode();

                    // reservaAPIvar
                    var SearchAdress = await response.Content.ReadAsAsync<SearchDTO>();

                    // Request para pegar nos ultimos 3 registos
                    var response2 = await client.GetAsync("https://localhost:44343/api/Searches/last/");

                    if (response2.IsSuccessStatusCode)
                    {
                        var readTask = response2.Content.ReadAsAsync<List<SearchDTO>>();

                        List<SearchDTO> reservas = readTask.Result.ToList();

                        if (checkResp != null || checkResp == true)
                        {
                            ViewBag.dist = true;

                            var convertMilesKm = new List<SearchDTO>();
                            foreach (var item in reservas)
                            {
                                convertMilesKm.Add(new SearchDTO
                                {
                                    PostCode = item.PostCode,
                                    City = item.City,
                                    Latitude = item.Latitude,
                                    Longitude = item.Longitude,
                                    Region = item.Region,
                                    SearchID = item.SearchID,
                                    DistanceToLondon = Math.Round(item.DistanceToLondon * 1.609344, 2)

                                });
                            }
                            reservas = convertMilesKm;
                        }
                        else
                        {
                            ViewBag.dist = false;
                        }

                        return View(reservas);
                    }
                    else
                    {
                        return View();
                    }
                }
            }
            catch (Exception ex)
            {
                ViewBag.codebool = false;

                return View();
            }
        }
    }
}

FrontEnd/FrontEnd/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@*<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>*@

FrontEnd/FrontEnd/Views/SearchDTO/Create.cshtml
@model FrontEnd.Models.SearchDTO

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>SearchDTO</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PostCode" class="control-label"></label>
                <input asp-for="PostCode" class="form-control" />
                <span asp-validation-for="PostCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Longitude" class="control-label"></label>
                <input asp-for="Longitude" class="form-control" />
                <span asp-validation-for="Longitude" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Latitude" class="control-label"></label>
                <input asp-for="Latitude" class="form-control" />
                <span asp-validation-for="Latitude" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Region" class="control-label"></label>
                <input asp-for="Region" class="form-control" />
                <span asp-validation-for="Region" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FrontEnd/FrontEnd/Views/SearchDTO/Delete.cshtml
@model FrontEnd.Models.SearchDTO

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SearchDTO</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PostCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PostCode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Longitude)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Longitude)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Latitude)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Latitude)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Region)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Region)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="SearchID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

FrontEnd/FrontEnd/Views/SearchDTO/Details.cshtml
@model FrontEnd.Models.SearchDTO

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>SearchDTO</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PostCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PostCode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Longitude)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Longitude)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Latitude)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Latitude)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Region)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Region)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.SearchID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

FrontEnd/FrontEnd/Views/SearchDTO/Edit.cshtml
@model FrontEnd.Models.SearchDTO

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>SearchDTO</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="SearchID" />
            <div class="form-group">
                <label asp-for="PostCode" class="control-label"></label>
                <input asp-for="PostCode" class="form-control" />
                <span asp-validation-for="PostCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Longitude" class="control-label"></label>
                <input asp-for="Longitude" class="form-control" />
                <span asp-validation-for="Longitude" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Latitude" class="control-label"></label>
                <input asp-for="Latitude" class="form-control" />
                <span asp-validation-for="Latitude" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Region" class="control-label"></label>
                <input asp-for="Region" class="form-control" />
                <span asp-validation-for="Region" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FrontEnd/FrontEnd/Views/SearchDTO/Index.cshtml
@model IEnumerable<FrontEnd.Models.SearchDTO>

@{
    ViewData["Title"] = "Index";
}

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        .alert {
            padding: 20px;
            background-color: #f44336;
            color: white;
        }

        .closebtn {
            margin-left: 15px;
            color: white;
            font-weight: bold;
            float: right;
            font-size: 22px;
            line-height: 20px;
            cursor: pointer;
            transition: 0.3s;
        }

            .closebtn:hover {
                color: black;
            }

        table {
            margin-top: 25px;
            font-family: arial, sans-serif;
            border-collapse: collapse;
            width: 100%;
            box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 8px;
        }

        td, th {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }

        tr:nth-child(even) {
            background-color: #dddddd;
        }



        input {
            box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 8px;
            width: 100%;
            border-width: 1px;
            /*border: 2px solid red;*/
            border-radius: 2px;
 
            }

        div3 {
            box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 8px;
            /*b*/ order: 1px solid black;
            padding: 20px;
            width: 200px;
            height: 200px;
            text-align: justify;
            
        }
    </style>
</head>



<form asp-action="Index" method="get">
    <div class="form-actions no-color">
        <p>
            Postal Code <input type="text" name="SearchString" classes="btn btn-default" value="@ViewData["CurrentFilter"]" />
            <input type="submit" value="Search" class="btn btn-default" />

            @if (ViewBag.dist == false || ViewBag.dist == null)
            {
                <div3>
                    <label style="margin-top: 25px;">
                        
                        <span>Check for KM results </span>
                        <input id="responsable" name="checkResp" value="false" type="checkbox" />
                    </label>
                </div3>
            }
            else
            {
                <div3>
                    <label style="margin-top: 25px;">
                        
                        <span>Check for KM results </span>

                        <input id="responsable" name="checkResp" value="true" type="checkbox" checked="checked" />
                        @*<th>Distance (KM)</th>*@
                    </label>
                </div3>
            }



        </p>

    </div>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PostCode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Region)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Latitude)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Longitude)
            </th>
            @if (ViewBag.dist == false || ViewBag.dist == null)
            {

                <th>Distance to Heathrow airport (MILES)</th>

            }
            else
            {

                <th>Distance to Heathrow airport (KM)</th>

            }

        </tr>
    </thead>
    <tbody>

        @if (Model != null)
        {
            foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.PostCode)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Region)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.City)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Latitude)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Longitude)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DistanceToLondon)
                    </td>

                </tr>

            }
        }
    </tbody>
</table>
@{ if (ViewBag.codebool == false)

    {

        <div class="alert">
            <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
            <strong>ERROR!</strong> Postal Code not Found (Check if API SERVICE is ON)
        </div>
    }


}

FrontEnd/FrontEnd/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FrontEnd</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>

    <header>


        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="w3-dropdown-hover"  asp-area="" asp-controller="SearchDTO" asp-action="Index" >Search Postal Code</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            
            <p style="color:Tomato;"><small>Esta aplicação faz requests à API denominada de 'Craft', esta última tem base de dados associada para obter persistência (executar Add-Migration/Update-Database) </small></p>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>